### ISSUE TITLE
How we can open multiple widgets?

### ISSUE THREAD

**Issue by SyedJamshedAli** [cmv/cmv-calcite-maps#10]
Right now, only one widget can open at a time. For example when we open Layers widget, and then if client on legend widget icon then legend widget simple replace the layers widget.
Please guide me.

**Comment by tmcgee** [comment]
@SyedJamshedAli I see you [posted](https://github.com/Esri/calcite-maps/issues/214) the same question in Esri's calcite-maps repo. Any changes to the existing Calcite Maps functionality would need to be addressed in that repo. I will close this issue and watch for Esri's response over there.

**Comment by SyedJamshedAli** [comment]
@tmcgee  can you please guide on this , No response on Calcite-maps repo.
Please help
