### ISSUE TITLE
the resources from cdn are not accessible 

### ISSUE THREAD

**Issue by gisfinder** [cmv/cmv-calcite-maps#12]
https://cdn.rawgit.com/cmv/cmv-app/develop/viewer/js/viewer/_ControllerBase.js
https://cdn.rawgit.com/cmv/cmv-app/develop/viewer/js/viewer/_ConfigMixin.js
https://cdn.rawgit.com/cmv/cmv-app/develop/viewer/js/viewer/_LayoutMixin.js

Putting these resources on local repository  will be better.

**Comment by tmcgee** [comment]
I appreciate your comment. We do need to consider alternative to rawgit in the future. While rawgit will eventually shutdown, each of these resources is still accessible via the CDN (has been tested from multiple locations). You can also use an alternative CDN such as jsdelivr.net:

- https://cdn.jsdelivr.net/gh/cmv/cmv-app@develop/viewer/js/viewer/_ControllerBase.js

For demonstration purposes which is the intent of this repository, it intentionally points to the most current version of CMV (develop branch). This keeps it simple for the maintainers of CMV and so we will likely continue to do that. You can always use whatever source you prefer. For a production deployment, I recommend you use the files locally on your own server.

**Comment by tmcgee** [comment]
All resources sourced from rawgit have been moved to jsdelivr.net.
