### ISSUE TITLE
Widgets remain gray after they are closed

### ISSUE THREAD

**Issue by MichelleJean28** [cmv/cmv-calcite-maps#2]
Hi @tmcgee , 

A few questions here, hope not too many.

1) The buttons in the menu remain active after closing the menu bar. Is this the default setting? 

![menu_widgets](https://cloud.githubusercontent.com/assets/25815540/23805796/0a3d49fe-05c8-11e7-9936-a53921120205.jpg)

2) I am trying to load a feature layer ([a polygon](http://www.arcgis.com/home/webmap/viewer.html?url=https://services3.arcgis.com/oO7KYsE1NxneFsw3/ArcGIS/rest/services/polygon/FeatureServer&source=sd))  but it is not showing up in the layers list. Am I doing something wrong here with my code? 
```
        operationalLayers: [{
            type: 'tiled',
            url: 'https://tiles.arcgis.com/tiles/oO7KYsE1NxneFsw3/arcgis/rest/services/ndvi/MapServer',
            title: 'ndvi1',
        },  {
            type: 'tiled',
            url: 'https://tiles.arcgis.com/tiles/oO7KYsE1NxneFsw3/arcgis/rest/services/ndvi/MapServer',
            title: 'ndvi2',
        },{
            type: 'feature',
            url: 'https://services3.arcgis.com/oO7KYsE1NxneFsw3/arcgis/rest/services/polygon/FeatureServer',
            title: 'polygon',
            options: {
                id: 'polygon',
                opacity: 1.0,
                visible: true,
                outFields: ['*'],
                mode: 2
            }
        }]
```

Thank you,
Michelle.

**Comment by roemhildtg** [comment]
@MichelleJean28 
1: That happens to me too. Looks like a bug. 
2: Features layers need the id at the end (in this case, 0): `https://services3.arcgis.com/oO7KYsE1NxneFsw3/ArcGIS/rest/services/polygon/FeatureServer/0`

**Comment by MichelleJean28** [comment]
Hi @roemhildtg ,

1) It does seem to be a bug
2) Got it, thanks :)

**Comment by tmcgee** [comment]
I believe this was fixed long ago - in either calcite maps or cmv-calcite-maps or both. Closing this issue. Can be re-opened if it is not resolved.
