### ISSUE TITLE
Custom basemap not working

### ISSUE THREAD

**Issue by mtabdar** [cmv/cmv-calcite-maps#3]
First thanks for the great app!
My problem is I could implement custom basemap in viewer.js of cmv but could not do the same in cmvcalcite. Both in local and disconnected environment.
In calcite i also have the fast font problem .
I would appreciate any help.

**Comment by tmcgee** [comment]
Hmmm. The configuration for the basemap widget is the same for both cmv and cmv+calcite. Could you please provide an example of a custom basemap that does not work in cmv-calcite?

**Comment by mtabdar** [comment]
The exact lines provided in basemap docs also created a cache tile in arcgis server and point the url to it. Let me mention that it seems that "Basemap" is not recognized although it is in both define and function of viewer.js

**Comment by mtabdar** [comment]
mapOptions: {
   basemap: new Basemap({
        id: 'basemap1',
        layers: [new BasemapLayer({
        url: 'http://ServerName/arcgis/rest/services/BaseMapName/MapServer'
        })]
    }),
    center: new Point({
        x: 6356023.515330248,
        y: 1917313.443425702,
        spatialReference: {
            wkid: 102642
        }
    }),
    zoom: 5,
    sliderStyle: 'small',
    showAttribution: true
}

**Comment by tmcgee** [comment]
If `Basemap` is not recognized, then there is a problem with the module(s) in the define or the perhaps more likely the arguments to the function at the top of viewer.js. Check the number and order of the arguments.

**Comment by mtabdar** [comment]
I checked but the issue remains. I noticed whichever of the three "basemap basemaplyer or point" is put first in function the issue arises at that one!
Anyway i found a workaround it i edited my local init.js file of arcgis js api and put my own url instead of street url and voila!
Thank you very much anyway
