### ISSUE TITLE
Streetview widget is not working

### ISSUE THREAD

**Issue by dawitmg** [cmv/cmv-calcite-maps#4]
Appreciating your efforts, the Streetview widget is not working even if i have used a working Google API key.

Thank you so much for your help.

Best Regards,
Dawit

**Comment by tmcgee** [comment]
The StreetView widget still not working with Calcite Maps (and other similar approaches) as the widget code is dependent on the TitlePane dijit. This should be fixed in the widget itself. Closing this issue since this is an issue for cmv-app, not specific to cmv-calcite-maps.
