### ISSUE TITLE
Menu in Layer Control Widget freezes open, won't close

### ISSUE THREAD

**Issue by jfaron** [cmv/cmv-calcite-maps#5]
When first opening the Layer Control widget, and clicking on the menu, the menu will not close when user clicks outside of menu. It seems that focus is required on one of the menu items in order for it to close when clicking outside of the menu, so if you right click in the menu after it is open, that will trigger focus on one of the items, then it will close as expected. Also, if the user closes the widget than reopens, it seems to also start working as expected, i.e. focus seems to happen automatically on the first item when user clicks on any layer's menu, and will close when the user clicks outside the menu. This happens on the Demo also, in Chrome and Firefox. I wonder if it is a Calcite issue, as this does not seem to be an issue on the standard viewer.
I've tried to search out issues with dojo menu and the only one I could find had to do with focus in the 'dijit/menu' that was a bug that was fixed a few years ago. Hopefully this won't be too hard to fix. The UI for the viewer in calcite maps is fantastic. Great job on this!

**Comment by jfaron** [comment]
This seems to be a Calcite issue. To see, go to Esri sample [https://developers.arcgis.com/javascript/3/sandbox/sandbox.html?sample=graphics_contextmenu](url) , change the two stylesheet links:
`<link rel="stylesheet" href= "https://js.arcgis.com/3.20/esri/themes/calcite/dijit/calcite.css">
    <link rel="stylesheet" href="https://js.arcgis.com/3.20/esri/themes/calcite/esri/esri.css">`

and the body class tag:
`<body class="calcite" style="font-size: 0.75em;">`

What happens is the first context menu that opens is not in focus, and thus clicking outside the popup menu does nothing. If you open a second menu by clicking a different graphic, then it gets focus and works as expected, or if you click in the popup it will also get focus. I'll create an issue in esri's calcite maps repo, since debugging this takes me into esri's minified code, into menu.js. It is just the sort of annoying bug that your boss will find within 30 seconds of using the app.

**Comment by tmcgee** [comment]
This may have been resolved in calcite maps. Closing since it not specifically an issue for cmv-calcite-maps.
