### ISSUE TITLE
dijit/form/DateTextBox not working with calcite

### ISSUE THREAD

**Issue by abbas-zaheer** [cmv/cmv-calcite-maps#8]
I am trying to use dijit/form/DateTextBox in Calcite but it is just rendering a simple textbox rather than a date selector. 

in HTML 

<input id="txtFromDate" name="fromDate"
            data-dojo-type="dijit/form/DateTextBox" />

**Comment by tmcgee** [comment]
@abbas-zaheer You should post questions about calcite maps at the [calcite-maps](https://github.com/Esri/calcite-maps) repo.
